apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-noticias-deployment
spec:
  selector:
    matchLabels:
      app: db-noticias
  template:
    metadata:
      labels:
        app: db-noticias
    spec:
      containers:
        - name: db-noticias-container
          image: aluracursos/mysql-db:1
          # resources:
          #   limits:
          #     memory: "128Mi"
          #     cpu: "500m"
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: db-configmap
