apiVersion: v1
kind: Pod
metadata:
  name: pod-volume
  labels:
    name: pod-volume
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      volumeMounts:
        - mountPath: pod-folder
          name: volume-pod
  volumes:
    - name: volume-pod
      hostPath:
        path: /home/volume-folder
        type: DirectoryOrCreate
